# Generated by Django 5.1.2 on 2025-07-21 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BMBCChecksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustingTube', models.CharField(max_length=100)),
                ('cylinderBody', models.CharField(max_length=100)),
                ('pistonTrunnion', models.CharField(max_length=100)),
                ('plungerSpring', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BogieChecksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axleGuide', models.CharField(max_length=100)),
                ('bogieFrameCondition', models.CharField(max_length=100)),
                ('bolster', models.CharField(max_length=100)),
                ('bolsterSuspensionBracket', models.CharField(max_length=100)),
                ('lowerSpringSeat', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BogieDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bogieNo', models.CharField(max_length=50)),
                ('dateOfIOH', models.DateField()),
                ('deficitComponents', models.CharField(max_length=255)),
                ('incomingDivAndDate', models.CharField(max_length=100)),
                ('makerYearBuilt', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WheelSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formNumber', models.CharField(max_length=100, unique=True)),
                ('submittedBy', models.CharField(max_length=100)),
                ('submittedDate', models.DateField()),
                ('status', models.CharField(default='Saved', max_length=50)),
                ('fields', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='BogieChecksheetForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formNumber', models.CharField(max_length=100, unique=True)),
                ('inspectionBy', models.CharField(max_length=100)),
                ('inspectionDate', models.DateField()),
                ('status', models.CharField(default='Saved', max_length=50)),
                ('bmbcChecksheet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='forms.bmbcchecksheet')),
                ('bogieChecksheet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='forms.bogiechecksheet')),
                ('bogieDetails', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='forms.bogiedetails')),
            ],
        ),
    ]
